services:
  - type: web
    name: gymbuddy-api
    env: node
    buildCommand: cd api && npm install && npm run build
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: gymbuddy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gymbuddy-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: gymbuddy-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: gymbuddy-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gymbuddy-db
          property: password

  - type: web
    name: gymbuddy-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://gymbuddy-api.onrender.com

databases:
  - name: gymbuddy-db
    databaseName: gymbuddy
    user: gymbuddy_user